import type { Metadata } from "next";
import "./globals.css";
import AuthSessionProvider from "./components/SessionProvider";
import nata from "./ui/fonts";
import "leaflet/dist/leaflet.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nata.className} antialiased`}>
        <AuthSessionProvider>{children}</AuthSessionProvider>
      </body>
    </html>
  );
}
